FROM node:20-alpine
WORKDIR /app
COPY .next ./.next
COPY node_modules ./node_modules
COPY package.json ./package.json
COPY next.config.js ./next.config.js
COPY messages ./messages
ENV NODE_ENV=production
ENV NEXT_PUBLIC_API_URL=auto
ENV NEXT_PUBLIC_AUTH_MODE=local
EXPOSE 3000
CMD ["npx", "next", "start"]
